### ISSUE TITLE
"DIP Pin 8 Etched" part not found

### ISSUE THREAD

**Issue by Ragooman** [OSHChip/OSHChip_V1.0_Docs#1]
Hello,
This is not really an issue but more of a question. 
I really like the use of the DIP style pin legs in your project. I've seen others before but they were not very compatible with both the breadboard and IC Sockets. As there were to thick and caused the contacts to spread out too much and eventually loosen the contacts. I think the type you have is a btter solution.
But I couldn't find the part mentioned in your BOM, "DIP Pin 8 Etched" at the listed supplier. I looked up Fliptronics but they don't seem to offer this on their website.
Is this a custom part or did they stop selling this ?
thanks,
Dan

**Comment by OSHChip-Owner** [comment]
Hi Dan,

The pins are custom designed and manufactured for OSHChip by Fliptronics (which is my consulting company). The square (some times gold plated) pins that everyone else seems to use are 0.025" square, and are difficult to push into the breadboards, and they damage the breadboard as you have observed. The OSHChip pins are made of [Nickel Silver](https://en.wikipedia.org/wiki/Nickel_silver) and are 0.010" thick. This material was selected for its shiny silver color and surface, ease of soldering, and material strength, and limited tolerance to being bent. The tail of the pin that goes into the breadboard are the same dimensions as standard DIP pins: 0.020" wide and 0.010" thick. This is what the breadboards were designed for, so OSHChips are relatively easy to insert and remove from a breadboard, and don't damage it any more than normal IC pins.

Quite a few people have expressed an interest in my custom pins, so I am going to be making them a product, but I have other OSHChip related challenges that are ahead of that.

Currently they are made as an 8 pin strip, with a supporting bar at the non-soldered end. After the other ends are soldered into the PCB, the  support bar is easily broken off by flexing it a few times. The joint from the pins to the support bar is deliberately weakened.

![arrayed_pins](https://cloud.githubusercontent.com/assets/13393668/13031186/54dd16f8-d278-11e5-9e9f-55748d077ea3.jpg)

**Comment by Ragooman** [comment]
This is great news. This reminds me of the IC socket pins I used long ago in the 70s for the kits we built. This was way cheaper than the plastic IC sockets. It was made the same way, each socket pin is individually fabricated, on a strip, came on a roll. Much like the molex connector socket pins except they were 100mil for DIPs. And so you just cutoff how much you needed for a 14pin, 16pin, etc. I look forward to when you add this to your online store. thanks !

**Comment by adrianfreed** [comment]
Hi, I am curious what the time line is for this interesting strip of pins you are planning to make available.

**Comment by OSHChip-Owner** [comment]
Hi Adrian,
About 3 months ago I had a Eureka moment and came up with a totally different way to make these pins, and much more importantly, a far superior way to hold them in alignment for soldering into a PCB. I then made the scary decision to pay for the tooling costs (NRE) and rather high minimum order quantities (MOQ) and the result is that about a week ago I received a bucket load of pin strips in lengths of 8, 14, and 20.  My current plan is to make them available via Tindie and maybe other distributors, around the end of August, or early September.  I am planning to price them per pin, but have not settled on final pricing.  If you have the time, and would be willing to discuss what you feel acceptable pricing should be, please call me on (408) 737-0295 afternoon or evening.  I would also be interested in how you would use them.

Thanks for your interest,
Philip

![first_test_of_new_pins](https://cloud.githubusercontent.com/assets/13393668/17159178/3a74229e-5350-11e6-894c-c4552684cfb5.JPG)

**Comment by adrianfreed** [comment]
thanks for the update.
I am looking at packaging some basic analog and cmos chips into  a dip format . One design has 16 pins, the other 24pins. I am struggling a bit because some of the chips I want to use aren't available in packages smaller than TSSOP which is a tight squeeze between those pin rows. QFN's are much easier to fit! My target retail price is $20-$25: so my price/pin hopes will be much in line with what you have been doing.

**Comment by OSHChip-Owner** [comment]
These Pins are now described on the main web site [Flip-Pins](http://oshchip.org/products/Flip-Pins_Product.html) and can be purchased on Tindie, or at Evil Mad Scientist Labs (EMSL) or at Sparkfun.
